[package]
name = "benchmark-types"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ahash = "0.8.12"
bytesize = { version = "2.1.0", features = ["serde"] }
chrono = { version = "0.4.42", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
