[package]
name = "turbostore-upload-objects"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
futures = { version = "0.3" }
tokio = { version = "1", features = ["full"] }
num-derive = "0.4"
num-traits = "0.2"
